services:
  figranium:
    image: ghcr.io/figranium/figranium:latest
    container_name: figranium
    ports:
      - "11345:11345"
      - "54311:54311"
    volumes:
      - ./data:/app/data
      - ./captures:/app/public/captures
      - ./captures:/app/src/public/captures
    environment:
      - PORT=11345
      - FIGRANIUM_RECORDINGS_TEMP_DIR=/app/data/recordings
      - FIGRANIUM_RECORDINGS_DIR=/app/public/captures
      - FIGRANIUM_SCREENSHOTS_TEMP_DIR=/app/data/screenshots
      - FIGRANIUM_SCREENSHOTS_DIR=/app/public/captures
      - FIGRANIUM_RECORDING_RETENTION_COUNT=10
    restart: unless-stopped
